2025-09-04 14:56:17,454 [INFO] loader:336 - Start wczytywania pliku: clickup_tasks_clean.xlsx
2025-09-04 14:56:18,184 [INFO] loader:341 - Wczytano arkusz: 1465 wierszy, 44 kolumn
2025-09-04 14:56:18,252 [DEBUG] loader:343 - Kolumny po czyszczeniu: ['ID', 'Nazwa', 'Status', 'Opis', 'Data utworzenia', 'Data aktualizacji', 'Przypisani', 'Category', 'Regulations accept', 'Merchant Group', 'Base. Account Type', 'Merchant mail', 'NIP', 'Merchant ID', 'Merchant Adres', 'Merchant Mail FV', 'Produkty Merchanta', 'Return Adres', 'Telefon', 'Website', 'Next Meeting Date:', 'Held first meeting', 'StatusBar Shortcut', 'Mail warunki', 'Warunki', 'Main Category', 'Merchant BL ID', 'Merchant KAM', 'Regulations email date sent', 'Merchant Information Form', 'SM Bestsellers upload', 'Merchant KAM (link)', 'Regulations accept date', 'Regulations Accept Relation', 'AVG Sent -> Accept', 'Listing ready Date', 'AVG Sent -> Listing', 'AVG Accept -> Listing', 'Akceptacja Regulaminu', 'SYNC WITH SM', 'Status', 'Price Check', 'Podmiana nazwy', 'Price Check fail Mail']
2025-09-04 14:56:18,262 [ERROR] loader:56 - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DELL\Documents\Skrypty\Skrypty-python-praca\zapis danych do bazy z clickupa\main.py", line 620, in <module>
    wczytaj_plik()
    ~~~~~~~~~~~~^^
  File "C:\Users\DELL\Documents\Skrypty\Skrypty-python-praca\zapis danych do bazy z clickupa\main.py", line 350, in wczytaj_plik
    df_norm["status"] = df["Status"].apply(lambda v: norm_text(v,55))
    ~~~~~~~^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 4316, in __setitem__
    self._set_item(key, value)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 4529, in _set_item
    value, refs = self._sanitize_column(value)
                  ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 5270, in _sanitize_column
    return _reindex_for_setitem(value, self.index)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 12699, in _reindex_for_setitem
    raise err
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\frame.py", line 12694, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
                      ~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\series.py", line 5164, in reindex
    return super().reindex(
           ~~~~~~~~~~~~~~~^
        index=index,
        ^^^^^^^^^^^^
    ...<5 lines>...
        tolerance=tolerance,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 5629, in reindex
    return self._reindex_axes(
           ~~~~~~~~~~~~~~~~~~^
        axes, level, limit, tolerance, method, fill_value, copy
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).__finalize__(self, method="reindex")
    ^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\generic.py", line 5652, in _reindex_axes
    new_index, indexer = ax.reindex(
                         ~~~~~~~~~~^
        labels, level=level, limit=limit, tolerance=tolerance, method=method
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\indexes\base.py", line 4436, in reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
2025-09-04 14:57:01,796 [INFO] loader:336 - Start wczytywania pliku: clickup_tasks_clean.xlsx
2025-09-04 14:57:02,352 [INFO] loader:341 - Wczytano arkusz: 1465 wierszy, 44 kolumn
2025-09-04 14:57:02,392 [DEBUG] loader:343 - Kolumny po czyszczeniu: ['ID', 'Nazwa', 'Status', 'Opis', 'Data utworzenia', 'Data aktualizacji', 'Przypisani', 'Category', 'Regulations accept', 'Merchant Group', 'Base. Account Type', 'Merchant mail', 'NIP', 'Merchant ID', 'Merchant Adres', 'Merchant Mail FV', 'Produkty Merchanta', 'Return Adres', 'Telefon', 'Website', 'Next Meeting Date:', 'Held first meeting', 'StatusBar Shortcut', 'Mail warunki', 'Warunki', 'Main Category', 'Merchant BL ID', 'Merchant KAM', 'Regulations email date sent', 'Merchant Information Form', 'SM Bestsellers upload', 'Merchant KAM (link)', 'Regulations accept date', 'Regulations Accept Relation', 'AVG Sent -> Accept', 'Listing ready Date', 'AVG Sent -> Listing', 'AVG Accept -> Listing', 'Akceptacja Regulaminu', 'SYNC WITH SM', 'relation statu', 'Price Check', 'Podmiana nazwy', 'Price Check fail Mail']
2025-09-04 14:57:02,699 [INFO] loader:390 - Znormalizowano: 1465 wierszy, 28 kolumn
2025-09-04 14:57:02,750 [ERROR] loader:56 - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DELL\Documents\Skrypty\Skrypty-python-praca\zapis danych do bazy z clickupa\main.py", line 620, in <module>
    wczytaj_plik()
    ~~~~~~~~~~~~^^
  File "C:\Users\DELL\Documents\Skrypty\Skrypty-python-praca\zapis danych do bazy z clickupa\main.py", line 460, in wczytaj_plik
    engine = create_engine(DB_URL, future=True, echo=False)
  File "<string>", line 2, in create_engine
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\create.py", line 564, in create_engine
    u = _url.make_url(url)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\url.py", line 860, in make_url
    raise exc.ArgumentError(
        f"Expected string or URL object, got {name_or_url!r}"
    )
sqlalchemy.exc.ArgumentError: Expected string or URL object, got None
2025-09-04 15:00:29,109 [INFO] loader:336 - Start wczytywania pliku: clickup_tasks_clean.xlsx
2025-09-04 15:00:29,623 [INFO] loader:341 - Wczytano arkusz: 1465 wierszy, 44 kolumn
2025-09-04 15:00:29,664 [DEBUG] loader:343 - Kolumny po czyszczeniu: ['ID', 'Nazwa', 'Status', 'Opis', 'Data utworzenia', 'Data aktualizacji', 'Przypisani', 'Category', 'Regulations accept', 'Merchant Group', 'Base. Account Type', 'Merchant mail', 'NIP', 'Merchant ID', 'Merchant Adres', 'Merchant Mail FV', 'Produkty Merchanta', 'Return Adres', 'Telefon', 'Website', 'Next Meeting Date:', 'Held first meeting', 'StatusBar Shortcut', 'Mail warunki', 'Warunki', 'Main Category', 'Merchant BL ID', 'Merchant KAM', 'Regulations email date sent', 'Merchant Information Form', 'SM Bestsellers upload', 'Merchant KAM (link)', 'Regulations accept date', 'Regulations Accept Relation', 'AVG Sent -> Accept', 'Listing ready Date', 'AVG Sent -> Listing', 'AVG Accept -> Listing', 'Akceptacja Regulaminu', 'SYNC WITH SM', 'relation statu', 'Price Check', 'Podmiana nazwy', 'Price Check fail Mail']
2025-09-04 15:00:29,958 [INFO] loader:390 - Znormalizowano: 1465 wierszy, 28 kolumn
2025-09-04 15:00:30,008 [ERROR] loader:56 - Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DELL\Documents\Skrypty\Skrypty-python-praca\zapis danych do bazy z clickupa\main.py", line 620, in <module>
    wczytaj_plik()
    ~~~~~~~~~~~~^^
  File "C:\Users\DELL\Documents\Skrypty\Skrypty-python-praca\zapis danych do bazy z clickupa\main.py", line 460, in wczytaj_plik
    engine = create_engine(DB_URL, future=True, echo=False)
  File "<string>", line 2, in create_engine
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\create.py", line 564, in create_engine
    u = _url.make_url(url)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\url.py", line 860, in make_url
    raise exc.ArgumentError(
        f"Expected string or URL object, got {name_or_url!r}"
    )
sqlalchemy.exc.ArgumentError: Expected string or URL object, got None
2025-09-04 15:02:21,918 [INFO] loader:336 - Start wczytywania pliku: clickup_tasks_clean.xlsx
2025-09-04 15:02:22,458 [INFO] loader:341 - Wczytano arkusz: 1465 wierszy, 44 kolumn
2025-09-04 15:02:22,501 [DEBUG] loader:343 - Kolumny po czyszczeniu: ['ID', 'Nazwa', 'Status', 'Opis', 'Data utworzenia', 'Data aktualizacji', 'Przypisani', 'Category', 'Regulations accept', 'Merchant Group', 'Base. Account Type', 'Merchant mail', 'NIP', 'Merchant ID', 'Merchant Adres', 'Merchant Mail FV', 'Produkty Merchanta', 'Return Adres', 'Telefon', 'Website', 'Next Meeting Date:', 'Held first meeting', 'StatusBar Shortcut', 'Mail warunki', 'Warunki', 'Main Category', 'Merchant BL ID', 'Merchant KAM', 'Regulations email date sent', 'Merchant Information Form', 'SM Bestsellers upload', 'Merchant KAM (link)', 'Regulations accept date', 'Regulations Accept Relation', 'AVG Sent -> Accept', 'Listing ready Date', 'AVG Sent -> Listing', 'AVG Accept -> Listing', 'Akceptacja Regulaminu', 'SYNC WITH SM', 'relation statu', 'Price Check', 'Podmiana nazwy', 'Price Check fail Mail']
2025-09-04 15:02:22,888 [INFO] loader:390 - Znormalizowano: 1465 wierszy, 28 kolumn
2025-09-04 15:02:23,117 [INFO] loader:281 - DIAG: brak oczywistych problemów typów w DF.
2025-09-04 15:02:24,215 [INFO] loader:558 - Wiersze z ustawionym relation_status: 1361
2025-09-04 15:02:24,218 [INFO] loader:566 - Próbka po UPSERCIE: [{'id': '86c1q4ztg', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q529h', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q5b48', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q5urg', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q65wk', 'status': 'merchant', 'relation_status': 13}]
2025-09-04 15:02:24,218 [INFO] loader:569 - KONIEC: 2.30 s (wierszy wejściowych: 1465)
2025-09-04 15:39:54,327 [INFO] loader:336 - Start wczytywania pliku: clickup_tasks_clean.xlsx
2025-09-04 15:39:54,851 [INFO] loader:341 - Wczytano arkusz: 1465 wierszy, 44 kolumn
2025-09-04 15:39:54,892 [DEBUG] loader:343 - Kolumny po czyszczeniu: ['ID', 'Nazwa', 'Status', 'Opis', 'Data utworzenia', 'Data aktualizacji', 'Przypisani', 'Category', 'Regulations accept', 'Merchant Group', 'Base. Account Type', 'Merchant mail', 'NIP', 'Merchant ID', 'Merchant Adres', 'Merchant Mail FV', 'Produkty Merchanta', 'Return Adres', 'Telefon', 'Website', 'Next Meeting Date:', 'Held first meeting', 'StatusBar Shortcut', 'Mail warunki', 'Warunki', 'Main Category', 'Merchant BL ID', 'Merchant KAM', 'Regulations email date sent', 'Merchant Information Form', 'SM Bestsellers upload', 'Merchant KAM (link)', 'Regulations accept date', 'Regulations Accept Relation', 'AVG Sent -> Accept', 'Listing ready Date', 'AVG Sent -> Listing', 'AVG Accept -> Listing', 'Akceptacja Regulaminu', 'SYNC WITH SM', 'relation statu', 'Price Check', 'Podmiana nazwy', 'Price Check fail Mail']
2025-09-04 15:39:55,189 [INFO] loader:390 - Znormalizowano: 1465 wierszy, 28 kolumn
2025-09-04 15:39:55,329 [INFO] loader:281 - DIAG: brak oczywistych problemów typów w DF.
2025-09-04 15:39:56,429 [INFO] loader:558 - Wiersze z ustawionym relation_status: 1361
2025-09-04 15:39:56,432 [INFO] loader:566 - Próbka po UPSERCIE: [{'id': '86c1q4ztg', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q529h', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q5b48', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q5urg', 'status': 'merchant', 'relation_status': 13}, {'id': '86c1q5wvt', 'status': 'premerchant', 'relation_status': None}]
2025-09-04 15:39:56,433 [INFO] loader:569 - KONIEC: 2.11 s (wierszy wejściowych: 1465)
